sonic-buildimage: Make sonic build with latest frr stable/3.0
RB=1267798
G=lnos-reviewers
R=ntrianta,zxu,rmolina,pmao
A=zxu

diff --git a/src/sonic-frr/Makefile b/src/sonic-frr/Makefile
--- a/src/sonic-frr/Makefile
+++ b/src/sonic-frr/Makefile
@@ -2,32 +2,59 @@
 SHELL = /bin/bash
 .SHELLFLAGS += -e
 
-MAIN_TARGET = frr_$(FRR_VERSION)_amd64.deb
+MAIN_TARGET = frr_$(FRR_VERSION)-1~sonic.debian8+1_amd64.deb
+
+DEBIAN8_DIR = debianpkg/backports/sonic.debian8/debian
+
+sed_gid_param = s/SONIC_USER_GID=.*/SONIC_USER_GID=${SONIC_USER_GID}/
+sed_uid_param = s/SONIC_USER_UID=.*/SONIC_USER_UID=${SONIC_USER_UID}/
 
 $(addprefix $(DEST)/, $(MAIN_TARGET)): $(DEST)/% :
 
-        # UID/GID env-vars must be explicitly passed to installation scripts to
-        # allow subsequent 'dpkg -i' process to make use of this variable.
-	if ! grep -q "^SONIC_USER_UID=" sonic_frr.preinst; then
-		sed -e"/^set -u/a SONIC_USER_GID=${SONIC_USER_GID}" \
-		    -e"/^set -u/a SONIC_USER_UID=${SONIC_USER_UID}" \
-		    sonic_frr.preinst > tmp_file && \
-		mv tmp_file sonic_frr.preinst
-	fi
-
 	pushd ./frr
 
-        # Replacing frr's rules/install/service files with SONiC's own versions
-        # to activate specific knobs and adjust install process to SONiC needs.
-	cp ../sonic_frr.rules debian/rules
-	cp ../sonic_frr.install debian/frr.install
-	cp ../sonic_frr.preinst debian/frr.preinst
-	cp ../sonic_frr.postinst debian/frr.postinst
-	cp ../sonic_frr.init.d.frr tools/frr
+	if [ ${SONIC_USER_GID}"unset" = "unset" ] || [ ${SONIC_USER_UID}"unset" = "unset" ]; then
+		sed -i "/SONIC_USER/d" $(DEBIAN8_DIR)/frr.preinst
+		if patch -Rsfp1 --dry-run < ../tools.frr.patch; then
+			patch -Rsfp1 < ../tools.frr.patch
+		fi
+	else
+		if ! grep -q "^SONIC_USER_GID=" $(DEBIAN8_DIR)/frr.preinst; then
+			sed -i "/^set -u/a SONIC_USER_GID=${SONIC_USER_GID}" $(DEBIAN8_DIR)/frr.preinst
+		else
+			sed -i "$(sed_gid_param)" $(DEBIAN8_DIR)/frr.preinst
+		fi
+
+		if ! grep -q "^SONIC_USER_UID=" $(DEBIAN8_DIR)/frr.preinst; then
+			sed -i "/^set -u/a SONIC_USER_UID=${SONIC_USER_UID}" $(DEBIAN8_DIR)/frr.preinst
+		else
+			sed -i "$(sed_uid_param)" $(DEBIAN8_DIR)/frr.preinst
+		fi
+
+		if patch -sfp1 --dry-run < ../tools.frr.patch; then
+			patch -sfp1 < ../tools.frr.patch
+		else
+			if ! patch -Rsfp1 --dry-run < ../tools.frr.patch; then
+				echo "Error: Patch for tools/frr failed"
+				exit 1
+			fi
+		fi
+	fi
 
         # Build the package
-	rm -f debian/*.debhelper.log
+	rm -rf debian
+	./bootstrap.sh
+	./configure
+	make dist
+	cp -a debianpkg debian
+	make -f debian/rules backports
+	rm -rf frrpkg
+	mkdir frrpkg
+	tar xf frr_*.orig.tar.gz
+	cd frr*
+	tar xf ../frr_*sonic.debian8*.debian.tar.xz
 	dpkg-buildpackage -rfakeroot -b -us -uc
-	popd
-
+	cd ..
 	mv $* $(DEST)/
+
+	popd
